//! Build script: auto-discovers the embedded translation files.
//!
//! Every `lang/<locale>.json` in the crate root is compiled into the plugin
//! binary. Adding a new language file requires **no code changes** — just drop
//! the file into `lang/` and rebuild. The generated registry is included by
//! `src/i18n.rs` from `OUT_DIR`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set");
    let lang_dir = Path::new(&manifest_dir).join("lang");

    // Re-run when any language file is added, removed or modified.
    println!("cargo:rerun-if-changed=lang");

    let mut locales: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&lang_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_file() || path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                locales.push(stem.to_string());
            }
        }
    }
    locales.sort();

    let mut out = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// Embedded language files: `(locale, json)` pairs, one per `lang/<locale>.json`.\n\
         pub const EMBEDDED_LANGS: &[(&str, &str)] = &[\n",
    );
    for locale in &locales {
        // Absolute path so `include_str!` resolves regardless of OUT_DIR location.
        let file = lang_dir.join(format!("{locale}.json"));
        out.push_str(&format!(
            "    ({locale:?}, include_str!({:?})),\n",
            file.display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set");
    let dest = Path::new(&out_dir).join("embedded_langs.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
