//! Plugin translations, backed by Pumpkin's own host-side i18n registry.
//!
//! Pumpkin exposes its translation system to plugins through the `i18n` WIT
//! interface: a plugin registers flat JSON maps under a namespace
//! ([`i18n::load_translations`]), and `TextComponent::custom` components are
//! resolved by the host against that registry using the player's locale
//! before the text reaches the client. Missing translations fall back to
//! `en_us`, then to the raw key, so an incomplete language file can never
//! break a message.
//!
//! # Adding a language
//!
//! Drop a `lang/<locale>.json` file into the crate root (or, at runtime, into
//! `<plugin data folder>/lang/<locale>.json`) — no code changes required.
//! Embedded files are discovered by `build.rs`; data-folder files are scanned
//! on load and override the embedded ones.

use pumpkin_plugin_api::{common::Locale, i18n, text::TextComponent};
use std::fs;
use std::sync::OnceLock;

/// Namespace every plugin translation key lives under.
pub const NAMESPACE: &str = "pumpkin_voice";

/// Fallback if the configured server language cannot be read.
pub const FALLBACK_LOCALE: &str = "en_us";

// Auto-generated by build.rs: one entry per `lang/<locale>.json`.
include!(concat!(env!("OUT_DIR"), "/embedded_langs.rs"));

/// Server-side language (from the `language` config option), used for
/// registration-time strings (command and permission descriptions) and
/// console feedback. Player-facing messages always use the player's own
/// client locale instead.
static SERVER_LOCALE: OnceLock<String> = OnceLock::new();

/// Registers the embedded translations (and any overrides found in
/// `<data_folder>/lang/<locale>.json`) with the Pumpkin host.
///
/// Files loaded later overwrite earlier keys, so data-folder files override
/// the embedded defaults. Must be called once from `on_load` (after the
/// config is initialized) before any translated component is sent.
pub fn init(data_folder: &str) {
    let language = crate::config::CONFIG
        .read()
        .map(|config| config.language.clone())
        .unwrap_or_else(|_| FALLBACK_LOCALE.to_string());
    let _ = SERVER_LOCALE.set(language);

    for (locale, json) in EMBEDDED_LANGS {
        match locale_from_str(locale) {
            Some(wit_locale) => i18n::load_translations(NAMESPACE, json, wit_locale),
            None => tracing::warn!("Skipping embedded language file with unknown locale {locale}"),
        }
    }

    load_folder_overrides(data_folder);
}

/// The server-side language (config option `language`, default `en_us`).
#[must_use]
pub fn default_locale() -> &'static str {
    SERVER_LOCALE.get().map_or(FALLBACK_LOCALE, String::as_str)
}

/// Builds a translated text component for `key`, resolved in `locale`.
#[must_use]
pub fn tr(locale: &str, key: &str) -> TextComponent {
    TextComponent::custom(NAMESPACE, key, locale, Vec::new())
}

/// Builds a translated text component with sequential `%s` substitution
/// arguments.
#[must_use]
pub fn tr_with(locale: &str, key: &str, args: Vec<TextComponent>) -> TextComponent {
    TextComponent::custom(NAMESPACE, key, locale, args)
}

/// Resolves `key` to a plain translated string, for APIs that take raw
/// strings instead of text components (e.g. command and permission
/// descriptions, Bedrock kick messages).
#[must_use]
pub fn translate_str(locale: &str, key: &str) -> String {
    let locale = locale_from_str(locale).unwrap_or(Locale::EnUs);
    i18n::translate(&format!("{NAMESPACE}:{key}"), locale)
}

/// Loads `lang/<locale>.json` overrides from the plugin data folder.
fn load_folder_overrides(data_folder: &str) {
    let normalized = data_folder.replace('\\', "/");
    let cleaned = normalized.trim_matches('/');
    if cleaned.is_empty() {
        return;
    }

    let dir = std::path::Path::new(cleaned).join("lang");
    let Ok(entries) = fs::read_dir(&dir) else {
        return; // No overrides folder: perfectly normal.
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() || path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let Some(locale) = locale_from_str(stem) else {
            tracing::warn!("Ignoring translation file with unsupported locale: {path:?}");
            continue;
        };
        match fs::read_to_string(&path) {
            Ok(json) => {
                i18n::load_translations(NAMESPACE, &json, locale);
                tracing::info!("Loaded voice chat translations for {stem} from {path:?}");
            }
            Err(err) => tracing::warn!("Failed to read translation file {path:?}: {err}"),
        }
    }
}

/// Maps a locale string (e.g. `en_us`) to the WIT locale enum.
///
/// Covers every locale the `pumpkin:plugin@0.1.0` WIT interface defines, so
/// any Minecraft-supported locale file loads without code changes. Unknown
/// locales fall back to `en_us` host-side anyway.
#[must_use]
fn locale_from_str(locale: &str) -> Option<Locale> {
    match locale.to_lowercase().as_str() {
        "af_za" => Some(Locale::AfZa),
        "ar_sa" => Some(Locale::ArSa),
        "ast_es" => Some(Locale::AstEs),
        "az_az" => Some(Locale::AzAz),
        "ba_ru" => Some(Locale::BaRu),
        "bar" => Some(Locale::Bar),
        "be_by" => Some(Locale::BeBy),
        "bg_bg" => Some(Locale::BgBg),
        "br_fr" => Some(Locale::BrFr),
        "brb" => Some(Locale::Brb),
        "bs_ba" => Some(Locale::BsBa),
        "ca_es" => Some(Locale::CaEs),
        "cs_cz" => Some(Locale::CsCz),
        "cy_gb" => Some(Locale::CyGb),
        "da_dk" => Some(Locale::DaDk),
        "de_at" => Some(Locale::DeAt),
        "de_ch" => Some(Locale::DeCh),
        "de_de" => Some(Locale::DeDe),
        "el_gr" => Some(Locale::ElGr),
        "en_au" => Some(Locale::EnAu),
        "en_ca" => Some(Locale::EnCa),
        "en_gb" => Some(Locale::EnGb),
        "en_nz" => Some(Locale::EnNz),
        "en_pt" => Some(Locale::EnPt),
        "en_ud" => Some(Locale::EnUd),
        "en_us" => Some(Locale::EnUs),
        "enp" => Some(Locale::Enp),
        "enws" => Some(Locale::Enws),
        "eo_uy" => Some(Locale::EoUy),
        "es_ar" => Some(Locale::EsAr),
        "es_cl" => Some(Locale::EsCl),
        "es_ec" => Some(Locale::EsEc),
        "es_es" => Some(Locale::EsEs),
        "es_mx" => Some(Locale::EsMx),
        "es_uy" => Some(Locale::EsUy),
        "es_ve" => Some(Locale::EsVe),
        "esan" => Some(Locale::Esan),
        "et_ee" => Some(Locale::EtEe),
        "eu_es" => Some(Locale::EuEs),
        "fa_ir" => Some(Locale::FaIr),
        "fi_fi" => Some(Locale::FiFi),
        "fil_ph" => Some(Locale::FilPh),
        "fo_fo" => Some(Locale::FoFo),
        "fr_ca" => Some(Locale::FrCa),
        "fr_fr" => Some(Locale::FrFr),
        "fra_de" => Some(Locale::FraDe),
        "fur_it" => Some(Locale::FurIt),
        "fy_nl" => Some(Locale::FyNl),
        "ga_ie" => Some(Locale::GaIe),
        "gd_gb" => Some(Locale::GdGb),
        "gl_es" => Some(Locale::GlEs),
        "haw_us" => Some(Locale::HawUs),
        "he_il" => Some(Locale::HeIl),
        "hi_in" => Some(Locale::HiIn),
        "hr_hr" => Some(Locale::HrHr),
        "hu_hu" => Some(Locale::HuHu),
        "hy_am" => Some(Locale::HyAm),
        "id_id" => Some(Locale::IdId),
        "ig_ng" => Some(Locale::IgNg),
        "io_en" => Some(Locale::IoEn),
        "is_is" => Some(Locale::IsIs),
        "isv" => Some(Locale::Isv),
        "it_it" => Some(Locale::ItIt),
        "ja_jp" => Some(Locale::JaJp),
        "jbo_en" => Some(Locale::JboEn),
        "ka_ge" => Some(Locale::KaGe),
        "kk_kz" => Some(Locale::KkKz),
        "kn_in" => Some(Locale::KnIn),
        "ko_kr" => Some(Locale::KoKr),
        "ksh" => Some(Locale::Ksh),
        "kw_gb" => Some(Locale::KwGb),
        "la_la" => Some(Locale::LaLa),
        "lb_lu" => Some(Locale::LbLu),
        "li_li" => Some(Locale::LiLi),
        "lmo" => Some(Locale::Lmo),
        "lo_la" => Some(Locale::LoLa),
        "lol_us" => Some(Locale::LolUs),
        "lt_lt" => Some(Locale::LtLt),
        "lv_lv" => Some(Locale::LvLv),
        "lzh" => Some(Locale::Lzh),
        "mk_mk" => Some(Locale::MkMk),
        "mn_mn" => Some(Locale::MnMn),
        "ms_my" => Some(Locale::MsMy),
        "mt_mt" => Some(Locale::MtMt),
        "nah" => Some(Locale::Nah),
        "nds_de" => Some(Locale::NdsDe),
        "nl_be" => Some(Locale::NlBe),
        "nl_nl" => Some(Locale::NlNl),
        "nn_no" => Some(Locale::NnNo),
        "no_no" => Some(Locale::NoNo),
        "oc_fr" => Some(Locale::OcFr),
        "ovd" => Some(Locale::Ovd),
        "pl_pl" => Some(Locale::PlPl),
        "pt_br" => Some(Locale::PtBr),
        "pt_pt" => Some(Locale::PtPt),
        "qya_aa" => Some(Locale::QyaAa),
        "ro_ro" => Some(Locale::RoRo),
        "rpr" => Some(Locale::Rpr),
        "ru_ru" => Some(Locale::RuRu),
        "ry_ua" => Some(Locale::RyUa),
        "sah_sah" => Some(Locale::SahSah),
        "se_no" => Some(Locale::SeNo),
        "sk_sk" => Some(Locale::SkSk),
        "sl_si" => Some(Locale::SlSi),
        "so_so" => Some(Locale::SoSo),
        "sq_al" => Some(Locale::SqAl),
        "sr_cs" => Some(Locale::SrCs),
        "sr_sp" => Some(Locale::SrSp),
        "sv_se" => Some(Locale::SvSe),
        "sxu" => Some(Locale::Sxu),
        "szl" => Some(Locale::Szl),
        "ta_in" => Some(Locale::TaIn),
        "th_th" => Some(Locale::ThTh),
        "tl_ph" => Some(Locale::TlPh),
        "tlh_aa" => Some(Locale::TlhAa),
        "tok" => Some(Locale::Tok),
        "tr_tr" => Some(Locale::TrTr),
        "tt_ru" => Some(Locale::TtRu),
        "uk_ua" => Some(Locale::UkUa),
        "val_es" => Some(Locale::ValEs),
        "vec_it" => Some(Locale::VecIt),
        "vi_vn" => Some(Locale::ViVn),
        "yi_de" => Some(Locale::YiDe),
        "yo_ng" => Some(Locale::YoNg),
        "zh_cn" => Some(Locale::ZhCn),
        "zh_hk" => Some(Locale::ZhHk),
        "zh_tw" => Some(Locale::ZhTw),
        "zlm_arab" => Some(Locale::ZlmArab),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::{EMBEDDED_LANGS, locale_from_str};
    use std::collections::HashMap;

    fn parse(json: &str) -> HashMap<String, String> {
        serde_json::from_str(json).unwrap_or_else(|e| panic!("invalid language file: {e}"))
    }

    #[test]
    fn embedded_language_files_are_valid_and_non_empty() {
        // The host parses these with `unwrap_or_default`, so a broken file
        // would silently register zero translations.
        assert!(!EMBEDDED_LANGS.is_empty(), "no embedded language files found");
        for (locale, json) in EMBEDDED_LANGS {
            let map = parse(json);
            assert!(!map.is_empty(), "{locale} contains no translations");
        }
    }

    #[test]
    fn every_locale_defines_the_same_keys() {
        let (_, reference) = EMBEDDED_LANGS
            .iter()
            .find(|(locale, _)| *locale == "en_us")
            .expect("en_us.json is the fallback and must exist");
        let mut reference: Vec<_> = parse(reference).keys().cloned().collect();
        reference.sort_unstable();

        for (locale, json) in EMBEDDED_LANGS {
            let mut keys: Vec<_> = parse(json).keys().cloned().collect();
            keys.sort_unstable();
            assert_eq!(
                keys, reference,
                "translation keys in {locale} drifted from en_us"
            );
        }
    }

    #[test]
    fn every_embedded_locale_is_supported() {
        // A file named e.g. `en-US.json` would be silently skipped at load
        // time; catch that here instead.
        for (locale, _) in EMBEDDED_LANGS {
            assert!(
                locale_from_str(locale).is_some(),
                "unsupported locale file name: {locale}"
            );
        }
    }
}
